image:
  # See https://hub.docker.com/r/alertlogic/al-agent-container/tags for available images
  repository: alertlogic/al-agent-container
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources:
  requests:
    memory: "100Mi"
    cpu: "0.25"
  limits:
    memory: "500Mi"
    cpu: "3"

tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
  # If you want the agent to be deployed on all agents with any posible taints,
  # use this one instead:
  # - operator: "Exists"

mounts:
  # Specify the socket name to mount for container engine integration
  # For Docker:
  containerSocket: /var/run/docker.sock
  # For containerd:
  #containerSocket: /run/containerd/containerd.sock
  # For CRI-O:
  #containerSocket: /run/crio/crio.sock
  # For Bottlerocket OS with K8s versions 1.22 and below ONLY:
  #containerSocket: /run/containerd/containerd.sock
  #containerSocketFrom: /run/dockershim.sock

# You must override this value when deploying the chart for non-AWS/Azure
# deployments.
# registration_key: "your_registration_key_here"
