apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: al-agent-container
  name: al-agent-container
spec:
  selector:
    matchLabels:
      app: al-agent-container
  template:
    metadata:
      labels:
        app: al-agent-container
    spec:
      hostNetwork: true
      containers:
        - name: al-agent-container
          # See https://hub.docker.com/r/alertlogic/al-agent-container/tags for available images
          image: alertlogic/al-agent-container:latest
          resources:
            requests:
              memory: "100Mi"
              cpu: "0.25"
            limits:
              memory: "500Mi"
              cpu: "3"
          env:
            - name: KEY
              value: "your_registration_key_here"
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /run/crio/crio.sock
              name: container-sock-volume
            - mountPath: /host/proc
              name: docker-proc-volume
          imagePullPolicy: Always
      volumes:
        - name: container-sock-volume
          hostPath:
            path: /run/crio/crio.sock
            type: Socket
        - name: docker-proc-volume
          hostPath:
            path: /proc
            type: Directory
      restartPolicy: Always
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      # If you want the agent to be deployed on all agents with any posible taints,
      # use this one instead:
      # - operator: "Exists"
